#!/usr/bin/env bash

###########
# Recipe Name: codespaces
# Description: Setup codespaces default image
###########

# Recipe configuration
AUTOCHOOSE_PLATFORM_RECIPE=false

# APT packages
APT=true
APT_CLEAN=true
APT_INSTALL_PACKAGES=(
    bat
    curl
    git
    jq
    shellcheck
    stow
    tmux
    wget
    zsh
)
APT_REMOVE_PACKAGES=()
APT_UPGRADE=true

# atuin
INSTALL_ATUIN=true

# homebrew configuration
INSTALL_HOMEBREW=false

# zsh
INSTALL_OH_MY_ZSH=true

# stow
STOW_PACKAGES=(
    atuin
    oh-my-zsh
    tmux
    zsh
    zsh-codespace
)
