#!/usr/bin/env bash

###########
# Recipe Name: default
# Description: Default recipe configuration
###########

# Recipe configuration
AUTOCHOOSE_PLATFORM_RECIPE=true

# APT packages
SETUP_APT=false
APT_CLEAN=false
APT_INSTALL_PACKAGES=()
APT_REMOVE_PACKAGES=()
APT_UPGRADE=false

# atuin
INSTALL_ATUIN=false

# homebrew configuration
INSTALL_HOMEBREW=false

# MACOS
CONFIGURE_MACOS_SYSTEM=false
SET_MACOS_HOSTNAME="${MACOS_HOSTNAME:-None}"

# nvim
INSTALL_NVIM=false

# stow
STOW_PACKAGES=()

# sudo
SUDO_UP_FRONT=false

# zsh
SETUP_ZSH=true
INSTALL_OH_MY_ZSH=false
