#!/usr/bin/env bash

###########
# Recipe Name: macosx
# Description: First time setup for macbooks
###########

# setup configuration
AUTOMATICALLY_CHOOSE_RECIPE=false

# homebrew configuration
INSTALL_HOMEBREW=true
HOMEBREW_BUNDLE_FILE="./Brewfile"

# zsh
INSTALL_OH_MY_ZSH=true

# stow
STOW_PACKAGES=(
    zsh
    zsh-osx
)
