#!/usr/bin/env bash

###########
# Recipe Name: macosx
# Description: First time setup for macbooks
###########

# Recipe configuration
AUTOCHOOSE_PLATFORM_RECIPE=false

# APT packages
APT_CLEAN=false
APT_INSTALL_PACKAGES=()
APT_REMOVE_PACKAGES=()
APT_UPGRADE=false

# atuin
INSTALL_ATUIN=false

# homebrew configuration
INSTALL_HOMEBREW=true
HOMEBREW_BUNDLE_FILE="./Brewfile"

# zsh
INSTALL_OH_MY_ZSH=true

# stow
STOW_PACKAGES=(
    atuin
    zsh
    zsh-osx
)
