#!/usr/bin/env bash

###########
# Recipe Name: macosx
# Description: First time setup for macbooks
###########

# shellcheck shell=bash
# shellcheck disable=SC2034

# APT packages
SETUP_APT=false
APT_CLEAN=false
APT_INSTALL_PACKAGES=()
APT_REMOVE_PACKAGES=()
APT_UPGRADE=false

# atuin
SETUP_ATUIN=false # Atuin is installed via brew

# codex
SETUP_CODEX_CLI=false

# codespaces
SETUP_CODESPACES_SYSTEM=false

# hashicorp
SETUP_HASHI_APT_REPO=false

# homebrew configuration
SETUP_HOMEBREW=true
HOMEBREW_BUNDLE_FILE="./Brewfile"

# MACOS
SETUP_MACOS_SYSTEM=true
SET_MACOS_HOSTNAME="${MACOS_HOSTNAME:-None}"

# nvim
SETUP_NVIM=false

# sudo
SUDO_UP_FRONT=false

# stow
STOW_PACKAGES=(
    atuin
    gitconfig-osx
    kitty
    neovim
    oh-my-zsh
    tmux
    zsh
    zsh-osx
    ssh-osx
)

# yq
SETUP_YQ=false

# zsh
SETUP_ZSH=true
SETUP_OH_MY_ZSH=true

# astral.sh tools
SETUP_ASTRAL_SH_TOOLS=false
