#!/usr/bin/env bash

set -u

## Globals ##
RECIPE_DIR="${RECIPE_DIR:-./recipes}"
TARGET_RECIPE_NAME="${TARGET_RECIPE_NAME:-default}"
SETUP_AUTOCHOOSE_RECIPE="${SETUP_AUTOCHOOSE_RECIPE:-true}"

## functions ##
source scripts/common.sh

## Main ##
# Load recipe
if "${SETUP_AUTOCHOOSE_RECIPE}"; then
    # Platform
    KERNEL_NAME="$(uname -s)"
    CODESPACES="${CODESPACES:-false}"

    case $KERNEL_NAME in
        Darwin)
            platform_recipe="macosx"
            ;;
        Linux)
            if "$CODESPACES"; then
                platform_recipe="codespaces"
            fi
            ;;
    esac

    echo_info "Using automatically chosen recipe: '$platform_recipe'"
    source_recipe "$platform_recipe"
else
    echo_info "Using configured target recipe: '$TARGET_RECIPE_NAME'"
    source_recipe "${TARGET_RECIPE_NAME}"
fi

# sudo
if "${SUDO_UP_FRONT}"; then
    echo_info "Requesting sudo password to cache credentials for script run duration"
    sudo_up_front
fi

# zsh
if "${SETUP_ZSH}"; then
    echo_info "Configure zsh"

    mkdir -p "$HOME/.zshrc.d"
    mkdir -p "$HOME/.local/share/zsh/completions"

    if "${SETUP_OH_MY_ZSH}"; then
        echo_info "Install oh-my-zsh"
        ./scripts/oh-my-zsh.sh install
    fi
fi

# hashicorp
if "${SETUP_HASHI_APT_REPO}"; then
    echo_info "Configure the HashiCorp apt repository"
    ./scripts/hashi_apt_repo.sh configure
fi

# apt
if "${SETUP_APT}"; then
    echo_info "Install / remove / upgrade apt packages"

    if [ -n "${APT_INSTALL_PACKAGES[*]:-}" ]; then
        ./scripts/apt.sh install "${APT_INSTALL_PACKAGES[@]}"
    fi

    if [ -n "${APT_REMOVE_PACKAGES[*]:-}" ]; then
        ./scripts/apt.sh remove "${APT_INSTALL_PACKAGES[@]}"
    fi

    if "${APT_UPGRADE}"; then
        ./scripts/apt.sh upgrade
    fi

    if "${APT_CLEAN}"; then
        ./scripts/apt.sh clean
    fi
fi

# homebrew
if "${SETUP_HOMEBREW}"; then
    echo_info "Install and configure homebrew"

    ./scripts/homebrew.sh install
    eval "$(/opt/homebrew/bin/brew shellenv)"

    if [ -f "${HOMEBREW_BUNDLE_FILE:-}" ]; then
        echo_info "Install homebrew bundle"
        ./scripts/homebrew.sh bundle
    fi
fi

# stow
if [ -n "${STOW_PACKAGES[*]:-}" ]; then
    echo_info "Install requested dotfiles packages via stow"
    ./scripts/stow.sh install "${STOW_PACKAGES[@]}"
fi

# atuin
if [ -n "${SETUP_ATUIN}" ]; then
    echo_info "Setting up atuin"
    ./scripts/atuin.sh install
fi

# nvim
if "${SETUP_NVIM}"; then
    echo_info "Installing the latest nvim binary release"
    ./scripts/neovim.sh install
fi

# yq
if "${SETUP_YQ}"; then
    echo_info "Installing yq"
    ./scripts/yq.sh install
fi

# macos
if "${SETUP_MACOS_SYSTEM}"; then
    if [ ! "${SET_MACOS_HOSTNAME}" == "None" ]; then
        echo_info "Set macOS hostname to: ${SET_MACOS_HOSTNAME}"
        ./scripts/macos.sh hostname "${SET_MACOS_HOSTNAME}"
    fi

    echo_info "Configure macOS system settings"
    ./scripts/macos.sh configure
fi
